In [1]:
from IPython.display import Image, display
import numpy as np
import pandas as pd

display(Image(url='https://www.python.org/static/img/python-logo.png'))

In [12]:
# pip install openpyxl
pd.read_excel('data/example.xlsx')

   Num  Name Grade
0    1   Kim    A+
1    2   Lee     A
2    3  Park     B

In [21]:
# 시트이름으로 불러오기
pd.read_excel('data/example.xlsx', sheet_name='2nd Sheet')

    과일     가격   색
0   레몬   1000  노랑
1  바나나    800  노랑
2    귤    500  주황
3   체리  10000  빨강
4   키위   6000  초록

In [22]:
# 번호로 불러오기 (시작이 0)
pd.read_excel('data/example.xlsx', sheet_name = 0)

   Num  Name Grade
0    1   Kim    A+
1    2   Lee     A
2    3  Park     B

In [26]:
# header : 열 이름(헤더)으로 사용할 행 지정 / 첫 행이 헤더가 아닌 경우 header = None

pd.read_excel('data/example.xlsx', header = 1)

   1   Kim A+
0  2   Lee  A
1  3  Park  B

In [28]:
# names : 열 이름을 지정. 불어오는 열의 개수와 일치해야 한다.
pd.read_excel('data/example.xlsx', names = ['col1', 'col2'])

   col1 col2
1   Kim   A+
2   Lee    A
3  Park    B

In [29]:
# usecols : 불러올 열 지정
pd.read_excel('data/example.xlsx', usecols = ['Name', 'Grade'])

   Name Grade
0   Kim    A+
1   Lee     A
2  Park     B

In [31]:
# usecols : 번호로 지정
pd.read_excel('data/example.xlsx', usecols = [1, 2])

   Name Grade
0   Kim    A+
1   Lee     A
2  Park     B

In [33]:
# na_values : 결측치로 사용할 값 지정
pd.read_excel('data/example.xlsx', sheet_name=2, na_values = ['-', 'NA'])

   Num  Name Grade
0    1   Kim    A+
1    2   Lee     C
2    3  Park   NaN

In [34]:
# nrows : 불러올 행 개수 제한 / 처음 ~ n 번째 행까지 불러오기
pd.read_excel('data/example.xlsx', nrows=2)

   Num Name Grade
0    1  Kim    A+
1    2  Lee     A

In [35]:
# skiprows : 불러올 때 건너뛸 행 지정
pd.read_excel('data/example.xlsx', skiprows=2)

   2   Lee  A
0  3  Park  B

In [36]:
# skipfooter : 불러올 때 건너뛸 행 지정 (마지막 n 행)
pd.read_excel('data/example.xlsx', skipfooter=2)

   Num Name Grade
0    1  Kim    A+